const CATALOG = [
    {
        id: "el1",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 13599,
        i:0,
    },
    {
        id: "el2",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 1359,
        i:1,
    },
    {
        id: "el3",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 3599,
        i:2,
    },
    {
        id: "el4",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 17599,
        i:3,
    },
    {
        id: "el5",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 14599,
        i:4,
    },
    {
        id: "el6",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 18599 ,
        i:5,
    },
    {
        id: "el7",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 1359 ,
        i:6,
    },
    {
        id: "el8",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 1599 ,
        i:7,
    },
    {
        id: "el9",
        img: '../img/pc.png',
        text: 'Windows 10 Домашняя 1366x768 Пикс 15.6" 1.1 ГГц Intel Celeron N4020 4 ГБ DDR4 SSD 256 ГБ Intel UHD Graphics 600Серый',
        price: 1399 ,
        i:8,
    },
];
const CATALOG_PHONE =[
    {
        id: "el1",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 74180,
    },
    {
        id: "el2",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 73180,
    },
    {
        id: "el3",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 72180,
    },
    {
        id: "el4",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 115180,
    },
    {
        id: "el5",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 104180,
    },
    {
        id: "el6",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 94180 ,
    },
    {
        id: "el7",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 84180 ,
    },
    {
        id: "el8",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 77180 ,
    },
    {
        id: "el9",
        img: '../img/phone.png',
        text: 'iPhone iOS 15 6.1", OLED 2532x1170 Apple A15 Bionic, 6-ти ядерный 128 ГБ',
        price: 75180,
    },
];
const CATALOG_TEHNIC =[
    {
        id: "el1",
        img: '../img/tehnic.png',
        text: 'Объем, л 1.5 Мощность, Вт 2400 Металл Подсветка Закрытая спираль Автоотключение Выбор температуры нагрева, Встроенный термометр',
        price: 21990,
    },
    {
        id: "el2",
        img: '../img/tehnic.png',
        text: 'Объем, л 1.5 Мощность, Вт 2400 Металл Подсветка Закрытая спираль Автоотключение Выбор температуры нагрева, Встроенный термометр',
        price: 21990,
    },
    {
        id: "el3",
        img: '../img/tehnic.png',
        text: 'Объем, л 1.5 Мощность, Вт 2400 Металл Подсветка Закрытая спираль Автоотключение Выбор температуры нагрева, Встроенный термометр',
        price: 21990,
    },
    {
        id: "el4",
        img: '../img/tehnic.png',
        text: 'Объем, л 1.5 Мощность, Вт 2400 Металл Подсветка Закрытая спираль Автоотключение Выбор температуры нагрева, Встроенный термометр',
        price: 21990,
    },
    {
        id: "el5",
        img: '../img/tehnic.png',
        text: 'Объем, л 1.5 Мощность, Вт 2400 Металл Подсветка Закрытая спираль Автоотключение Выбор температуры нагрева, Встроенный термометр',
        price: 21990,
    },
    {
        id: "el6",
        img: '../img/tehnic.png',
        text: 'Объем, л 1.5 Мощность, Вт 2400 Металл Подсветка Закрытая спираль Автоотключение Выбор температуры нагрева, Встроенный термометр',
        price: 21990,
    },
];
const CATALOG_INSTRUMENTS =[
    {
        id: "el1",
        img: '../img/instrument.png',
        text: 'инструменты: молоток, отвёртки, рукоять для бит, вороток для головок, трещотка, ключи гаечные оснастка: биты, торцевые головки',
        price: 17900,
    },
    {
        id: "el2",
        img: '../img/instrument.png',
        text: 'инструменты: молоток, отвёртки, рукоять для бит, вороток для головок, трещотка, ключи гаечные оснастка: биты, торцевые головки',
        price: 17900,
    },
    {
        id: "el3",
        img: '../img/instrument.png',
        text: 'инструменты: молоток, отвёртки, рукоять для бит, вороток для головок, трещотка, ключи гаечные оснастка: биты, торцевые головки',
        price: 17900,
    },
    {
        id: "el4",
        img: '../img/instrument.png',
        text: 'инструменты: молоток, отвёртки, рукоять для бит, вороток для головок, трещотка, ключи гаечные оснастка: биты, торцевые головки',
        price: 17900,
    },
    {
        id: "el5",
        img: '../img/instrument.png',
        text: 'инструменты: молоток, отвёртки, рукоять для бит, вороток для головок, трещотка, ключи гаечные оснастка: биты, торцевые головки',
        price: 17900,
    },
    {
        id: "el6",
        img: '../img/instrument.png',
        text: 'инструменты: молоток, отвёртки, рукоять для бит, вороток для головок, трещотка, ключи гаечные оснастка: биты, торцевые головки',
        price: 17900,
    },
];